[platformio]
default_envs = waveshare-s3-touch

[env:waveshare-s3-touch]
platform = espressif32@7.0.1
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_qspi
board_build.partitions = default_16MB.csv
build_src_filter = +<*> -<legacy_main.cpp>
build_flags =
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D BRELOCK_WAVESHARE=1
    -D BRELOCK_DEBUG=1
    -D CORE_DEBUG_LEVEL=1
lib_deps =
    adafruit/Adafruit GC9A01A@1.1.0
    adafruit/Adafruit GFX Library@1.12.6
    adafruit/Adafruit BusIO@1.17.4

[env:esp32dev]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_src_filter = +<legacy_main.cpp>
build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D BRELOCK_DEBUG=1

; Przykład dla ESP32-C3 SuperMini:
; [env:esp32-c3-supermini]
; platform = espressif32
; board = seeed_xiao_esp32c3
; framework = arduino
; monitor_speed = 115200
; build_flags = -D BRELOCK_DEBUG=1 -D LED_BUILTIN=8
