[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D BRELOCK_DEBUG=1

; Przykład dla ESP32-C3 SuperMini:
; [env:esp32-c3-supermini]
; platform = espressif32
; board = seeed_xiao_esp32c3
; framework = arduino
; monitor_speed = 115200
; build_flags = -D BRELOCK_DEBUG=1 -D LED_BUILTIN=8

